import { Router, type IRouter } from "express";
import healthRouter from "./health";
import playersRouter from "./players";
import teamsRouter from "./teams";
import gamesRouter from "./games";
import ppLinesRouter from "./pp-lines";
import externalLinesRouter from "./external-lines";
import projectionsRouter from "./projections";
import injuriesRouter from "./injuries";
import lineupConfirmationsRouter from "./lineup-confirmations";
import propScoresRouter from "./prop-scores";
import slateRouter from "./slate";
import entriesRouter from "./entries";
import watchlistRouter from "./watchlist";
import alertsRouter from "./alerts";
import dataPullLogsRouter from "./data-pull-logs";
import payoutConfigRouter from "./payout-config";
import dashboardRouter from "./dashboard";
import reviewRouter from "./review";
import dataHealthRouter from "./data-health";
import syncRouter from "./sync";
import explainRouter from "./explain";
import anthropicRouter from "./anthropic";
import marketIntelRouter from "./market-intel";
import streaksRouter from "./streaks";
import clvRouter from "./clv";
import matchupRouter from "./matchup";
import debugRouter from "./debug";
import varianceRouter from "./variance";
import userSettingsRouter from "./user-settings";
import lineupFactoryRouter from "./lineup-factory";
import fatigueRouter from "./fatigue";
import calibrationRouter from "./calibration";
import systemHealthRouter from "./system-health";
import sharkRouter from "./shark";
import simulationRouter from "./simulation";
import historicalHitRatesRouter from "./historical-hit-rates";
import platformLinesRouter from "./platform-lines";
import paceRouter from "./pace";
import sharpRouter from "./sharp";
import nflAdvancedRouter from "./nfl-advanced";

const router: IRouter = Router();

router.use(healthRouter);
router.use(playersRouter);
router.use(teamsRouter);
router.use(gamesRouter);
router.use(ppLinesRouter);
router.use(externalLinesRouter);
router.use(projectionsRouter);
router.use(injuriesRouter);
router.use(lineupConfirmationsRouter);
router.use(propScoresRouter);
router.use(slateRouter);
router.use(entriesRouter);
router.use(watchlistRouter);
router.use(alertsRouter);
router.use(dataPullLogsRouter);
router.use(payoutConfigRouter);
router.use(dashboardRouter);
router.use(reviewRouter);
router.use(dataHealthRouter);
router.use(syncRouter);
router.use(explainRouter);
router.use(anthropicRouter);
router.use(marketIntelRouter);
router.use(streaksRouter);
router.use(clvRouter);
router.use(matchupRouter);
router.use(debugRouter);
router.use(varianceRouter);
router.use(userSettingsRouter);
router.use(lineupFactoryRouter);
router.use(fatigueRouter);
router.use(calibrationRouter);
router.use(systemHealthRouter);
router.use(sharkRouter);
router.use(simulationRouter);
router.use(historicalHitRatesRouter);
router.use(platformLinesRouter);
router.use(paceRouter);
router.use(sharpRouter);
router.use(nflAdvancedRouter);

export default router;
